# Generated by Django 3.2.11 on 2022-01-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_section',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_usn',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
