# Generated by Django 3.2.11 on 2022-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220118_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.TextField(default='')),
                ('test_description', models.TextField(max_length=7000)),
                ('passage', models.ManyToManyField(to='api.Passage')),
            ],
        ),
    ]
