# Generated by Django 3.2.11 on 2022-04-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220430_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
    ]
