# Generated by Django 3.2.11 on 2022-04-30 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.datetime_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20220430_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=utils.datetime_utils.datetime_now_plus_minutes),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
