# Generated by Django 3.2.11 on 2022-05-01 09:54

import datetime
from django.db import migrations, models
import utils.datetime_utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220430_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.TextField(default='')),
                ('quiz_description', models.TextField(max_length=7000)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=utils.datetime_utils.datetime_now_plus_minutes)),
                ('passage', models.ManyToManyField(to='api.Passage')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
