# Generated by Django 3.2.11 on 2022-06-12 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_quiz_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
